# AML 2203 Assignment 2
# Student ID - C0852435
# Student name - Yogesh Kumar

# Week 6

# Cleaning HTML Documents

In [1]:
import nltk
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text = "this is an example to extract n-grams"

#function to generate n-grams
def extarct_ngrams(data,num):
    n_grams = ngrams(nltk.word_tokenize(data), num)
    return [' '.join(grams) for grams in n_grams]

#4-grams
print(extarct_ngrams(text,4))
#5-grams
print(extarct_ngrams(text, 5))

['this is an example', 'is an example to', 'an example to extract', 'example to extract n-grams']
['this is an example to', 'is an example to extract', 'an example to extract n-grams']


# Word Tokenization

### Using word_tokenize

In [2]:
import nltk.tokenize as nt

text1 = "Hello everyone. Welcome to Word Tokenization"

words = nt.word_tokenize(text1)
print(words)

['Hello', 'everyone', '.', 'Welcome', 'to', 'Word', 'Tokenization']


### Using tokenize() 

In [3]:
import nltk.tokenize as nt

text1 = "Hello everyone. Welcome to Word Tokenization"

tokenizer = nt.TreebankWordTokenizer()
words1 = tokenizer.tokenize(text1)
print(words1)

['Hello', 'everyone.', 'Welcome', 'to', 'Word', 'Tokenization']


# Removal of Stop Words

In [4]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
print(stop_words)

{'for', 'are', 'with', 'needn', "needn't", "it's", "haven't", 'out', "you've", 'why', 'there', 'have', 'am', 'too', 'down', 'as', 'by', "doesn't", "won't", 'in', 'against', 'we', 'does', 'between', 'y', 'no', 'where', 'now', 'what', 'and', 'again', 'on', 'all', 'himself', 'myself', 'hers', 'its', 'i', "shan't", "you'd", 'those', 'to', 'both', 'doing', "don't", 'isn', 'themselves', 'do', "mightn't", 'll', 'but', 'shan', 'don', 'here', 'each', 'ain', 'is', 'or', 'the', 'if', 'about', 'during', 'their', "shouldn't", "didn't", 'into', "mustn't", 'who', 'while', 'nor', 'an', 'ma', 'above', 'from', 'after', 'be', 'our', 're', 'weren', "couldn't", 'has', 'haven', 'won', "weren't", 'mustn', 'few', 'so', "you're", 'wasn', 'her', 'then', 'were', 'that', 'did', 'him', 'ourselves', 'up', 'when', 'than', 'through', 'over', 'just', 'should', 'will', 'own', 'because', 'only', 'herself', 'below', 'off', 'how', 'yours', 'been', "wasn't", 'these', 'you', 'this', "you'll", 'itself', "wouldn't", 'm', 'me'

In [5]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

text = "There was no chance for any character development they were busy."
stop_words = set(stopwords.words('english'))
words = word_tokenize(text)
result = []
for w in words:
    if w not in stop_words:
        result.append(w)
        
print(words)
print(result)

['There', 'was', 'no', 'chance', 'for', 'any', 'character', 'development', 'they', 'were', 'busy', '.']
['There', 'chance', 'character', 'development', 'busy', '.']


# Stemming

In [6]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer

ps = PorterStemmer()
ls = LancasterStemmer()

words = ["program","programs","programmer","programming","destabilize"]

print('Porter Stemmer: ')
for w in words:
    print(w," : ",ps.stem(w))

print('\nLancaster Stemmer : ')
for w in words:
    print(w," : ",ls.stem(w))

Porter Stemmer: 
program  :  program
programs  :  program
programmer  :  programm
programming  :  program
destabilize  :  destabil

Lancaster Stemmer : 
program  :  program
programs  :  program
programmer  :  program
programming  :  program
destabilize  :  dest


# Bag of Words - NLTK

### 1. Preprocess the data

In [7]:
import nltk
import re
import numpy as np

text = """This movie made it into one of my top 10 most awful movies.
There wasn't a continous minute where there wasn't a fight with one monster or another.
There was no chance for any character development, they were too busy running from one sword fight to another.
I had no emotional attachment ( except to the big machine ## that wanted to destroy them)."""

data = nltk.sent_tokenize(text)
for i in range(len(data)):
    data[i] = data[i].lower()
    data[i] = re.sub(r'\W+',' ', data[i])
    data[i] = re.sub(r'\s+',' ', data[i])
    
for i in data:
    print(i)

this movie made it into one of my top 10 most awful movies 
there wasn t a continous minute where there wasn t a fight with one monster or another 
there was no chance for any character development they were too busy running from one sword fight to another 
i had no emotional attachment except to the big machine that wanted to destroy them 


### 2. Creation of Vocabulary

In [8]:
import heapq

wordcount = {}

for i in data:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in wordcount.keys():
            wordcount[word] = 1
        else:
            wordcount[word] += 1
            
print(len(wordcount))

freq_words = heapq.nlargest(30, wordcount, key=wordcount.get)
print(freq_words)

52
['one', 'there', 'to', 'wasn', 't', 'a', 'fight', 'another', 'no', 'this', 'movie', 'made', 'it', 'into', 'of', 'my', 'top', '10', 'most', 'awful', 'movies', 'continous', 'minute', 'where', 'with', 'monster', 'or', 'was', 'chance', 'for']


### 3. Creation of Vectors

In [9]:
x= []
for i in data:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(i):
            vector.append(1)
        else:
            vector.append(0)
    x.append(vector)
x = np.asarray(x)
print(x)

[[1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
